default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: mypassword
  pool: 20

development:
  <<: *default
  database: fore-webapp-development-new
